services:
  - type: web
    name: stake-arena
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.main:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
    autoDeploy: true
