services:
  - type: web
    name: stake-arena
    env: python
    runtime: python-3.12.3
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.main:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT"
    autoDeploy: true
